using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TPaintingCounter.Core.DataStructures
{
    public enum FileType : byte
    {
        None,
        Map,
        World,
        Player
    }
    public enum GameMode : int
    {
        Classic,
        Expert,
        Master,
        Journey
    }
    public enum LiquidType : byte
    {
        Water,
        Lava,
        Honey,
        Shimmer
    }
    [Flags]
    public enum WireType : byte
    {
        None,
        Red,
        Blue,
        Green,
        Yellow
    }
    public enum SlopeType : byte
    {
        Solid,
        SlopeDownLeft,
        SlopeDownRight,
        SlopeUpLeft,
        SlopeUpRight,
        HalfBlock
    }
    public enum PaintingType2x3 : ushort
    {
        Waldo = 0,
        Darkness = 1,
        DarkSoulReaper = 2,
        Land = 3,
        TrappedGhost = 4,
        AmericanExplosive = 5,
        GloriousNight = 6,
        BandageBoy = 7,
        DivineEye = 8,
        StudyOfABallAtRest = 9,
        GhostManifestation = 10,
        WickedUndead = 11,
        BloodyGoblet = 12,
        PaintingOfALass = 13,
        SufficientlyAdvanced = 14,
        StrangeGrowthOrange = 15,
        StrangeGrowthPurple = 16,
        StrangeGrowthRed = 17,
        StrangeGrowthGreen = 18,
        HappyLittleTree = 19,
        StrangeDeadFellows = 20,
        Secrets = 21,
        ThunderBolt = 22,
        Crustography = 23,
        TheWerewolf = 24,
        BlessingFromTheHeavens = 25,
        LoveIsInTheTrashSlot = 26,
        Fangs = 27,
        HailToTheKing = 28,
    }
    public enum PaintingType3x2 : ushort
    {
        DemonsEye = 0,
        FindingGold = 1,
        FirstEncounter = 2,
        GoodMorning = 3,
        UndergroundReward = 4,
        ThroughTheWindow = 5,
        PlaceAboveTheClouds = 6,
        DoNotStepOnTheGrass = 7,
        ColdWatersInTheWhiteLand = 8,
        LightlessChasms = 9,
        TheLandOfDeceivingLooks = 10,
        Daylight = 11,
        SecretOfTheSands = 12,
        DeadLandComesAlive = 13,
        EvilPresence = 14,
        SkyGuardian = 15,
        LivingGore = 16,
        FlowingMagma = 17,
        TheDuplicityOfReflections = 19,
        StillLife = 20,
        SeeTheWorldForWhatItIs = 21,
        WhatLurksBelow = 22,
        ThisIsGettingOutOfHand = 23,
        Buddies = 24,
        MidnightSun = 25,
        CouchGag = 26,
        SilentFish = 27,
        TheDuke = 28,
        RoyalRomance = 29,
        Bioluminescence = 30,
        Wildflowers = 31,
        VikingVoyage = 32,
        Bifrost = 33,
        Heartlands = 34,
        ForestTroll = 35,
        AuroraBorealis = 36,
    }
    public enum PaintingType3x3 : ushort
    {
        BloodMoonRising = 12,
        TheHangedMan = 13,
        GloryOfTheFire = 14,
        BoneWarp = 15,
        SkellingtonJSkellingsworth = 18,
        TheCursedMan = 19,
        Sunflowers = 20,
        TerrarianGothic = 21,
        GuidePicasso = 22,
        TheGuardiansGaze = 23,
        FatherOfSomeone = 24,
        NurseLisa = 25,
        Discover = 26,
        HandEarth = 27,
        OldMiner = 28,
        Skelehead = 29,
        Impface = 30,
        OminousPresence = 31,
        ShiningMoon = 32,
        TheMerchant = 33,
        CrownoDevoursHisLunch = 34,
        RareEnchantment = 35,
        AndrewSphinx = 63,
        WatchfulAntlion = 64,
        BurningSpirit = 65,
        JawsOfDeath = 66,
        TheSandsOfSlime = 67,
        SnakesIHateSnakes = 68,
        Fore = 69,
        Nevermore = 70,
        Reborn = 71,
        DarkSideOfTheHallow = 74,
        Outcast = 76,
        FairyGuides = 77,
        AHorribleNightForAlchemy = 78,
        MorningHunt = 79,
        SuspiciouslySparkly = 80,
        Requiem = 81,
        CatSword = 82,
        KargohsSummon = 83,
        HighPitch = 84,
        AMachineForTerrarians = 85,
        TerraBladeChronicles = 86,
        BennyWarhol = 87,
        LizardKing = 88,
        MySon = 89,
        Duality = 90,
        ParsecPals = 91,
        EyeOfTheSun = 92,
    }
    public enum PaintingType6x4 : ushort
    {
        TheEyeSeesTheEnd = 0,
        SomethingEvilIsWatchingYou = 1,
        TheTwinsHaveAwoken = 2,
        TheScreamer = 3,
        GoblinsPlayingPower = 4,
        Dryadisque = 5,
        Impact = 6,
        PoweredByBirds = 7,
        TheDestroyer = 8,
        ThePersistencyOfEyes = 9,
        UnicornCrossingTheHallows = 10,
        GreatWave = 11,
        StarryNight = 12,
        FacingTheCerebralMastermind = 13,
        LakeOfFire = 14,
        TrioSuperHeroes = 15,
        TheCreationOfTheGuide = 16,
        JackingSkeletron = 17,
        BitterHarvest = 18,
        BloodMoonCountess = 19,
        HallowsEve = 20,
        MorbidCuriosity = 21,
        TreasureMap = 25,
        PillaginMePixels = 26,
        CastleMarsberg = 27,
        MartiaLisa = 28,
        TheTruthIsUpThere = 29,
        Sparky = 30,
        Acorns = 31,
        ColdSnap = 32,
        CursedSaint = 33,
        Snowfellas = 34,
        TheSeason = 35,
        NotAKidNorASquid = 36,
        LifeAboveTheSand = 37,
        Oasis = 38,
        PrehistoryPreserved = 39,
        AncientTablet = 40,
        Uluru = 41,
        VisitingThePyramids = 42,
        TheRollingGreens = 43,
        Graveyard = 44,
        Princess64 = 45,
        TheGentlemanScientist = 46,
        TheFirestarter = 47,
        TheBereaved = 48,
        TheStrongman = 49,
        RemnantsOfDevotion = 50,
        NotSoLostInParadies = 51,
        OcularResonance = 52,
        WingsOfEvil = 53,
        Constellation = 54,
        EyezorHead = 55,
        DreadOfTheRedSea = 56,
        DoNotEatTheVileMushroom = 57,
        YuumaTheBlueTiger = 58,
        MoonmanAndCompany = 59,
        SunshineOfIsrapony = 60,
        Purity = 61,
        LadyOfTheLake = 62,
        rSlashTerraria = 63,
        PrincessStyle = 64,
        CheesyPizzaPoster = 65,
    }
}
